---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, производителю, наличию на складе и категории.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен иметь адаптивную вёрстку для мобильных устройств.
  - Сайт должен быть выполнен как SPA - приложение.
  - Сайт должен иметь английскую и русскую локализацию.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге.
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
  - Корзина должна хранится в сессии браузера.
  - Сайт должен иметь постраничный вывод товара.
